### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by a-moses**
their isn't any discount right now

### CODE REVIEW

**Comment by wjgilmore** [comment]
Whoops I apologize for that, I must have accidentally disabled it when in the Gumroad interface. Go ahead and give the code (easteregg) a try now.

**Comment by a-moses** [comment]
I'm sorry I could send an email on the subject

SORRY .

**Comment by wjgilmore** [comment]
No problem! Feel free to email me anytime with Laravel questions.

**Comment by a-moses** [comment]
just know still  is not code form  on Gumroad site  :(

**Pull request closed without merging**
